#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'

cookbook "apt"
cookbook "build-essential"
cookbook "git"
cookbook "java"
cookbook "mysql"
cookbook "nginx"
cookbook "openssl"
cookbook "php"
cookbook "php-fpm"
cookbook "postfix"
cookbook "postgresql"
cookbook "python"
cookbook "user"
cookbook "varnish"
cookbook "zsh"

cookbook "xfce4",
  :git => 'https://github.com/phlipper/chef-xfce4.git',
  :ref => 'master'

cookbook "latex",
  :git => 'https://github.com/goruha/chef-latex.git',
  :ref => 'master'

cookbook "latex-disser",
  :git => 'https://github.com/goruha/chef-latex-disser.git',
  :ref => 'master'

cookbook 'drush',
  :git => 'https://github.com/vasilykraev/chef-drush.git',
  :ref => 'master'

cookbook 'platform_packages',
  :git => 'git://github.com/fnichol/chef-platform_packages.git', 
  :ref => 'master'

cookbook 'postgis2',
  :git => 'git://github.com/vasilykraev/cookbook-postgis.git', 
  :ref => 'master'

cookbook 'phpmyadmin',
  :git => 'git://github.com/priestjim/chef-phpmyadmin.git', 
  :ref => 'master'

cookbook 'phppgadmin',
  :git => 'git://github.com/arnebrasseur/chef-phppgadmin.git',
  :ref => 'master'

cookbook 'webapp',
  :git => 'git@github.com:goruha/chef-webapp.git',
  :ref => 'develop'

cookbook 'apache2',
  :git => 'git@github.com:goruha/apache2.git',
  :ref => 'master'
